/**
 * @file src/utils/airports.ts
 * @description Airport code translation helpers for route/origin/destination display.
 */

const AIRPORT_LOOKUP: Record<string, string> = {
  "ABE": "Lehigh Valley International Airport",
  "ABI": "Abilene Regional Airport",
  "ABQ": "Albuquerque International Sunport Airport",
  "ABR": "Aberdeen Regional Airport",
  "ABY": "Southwest Georgia Regional Airport",
  "ACK": "Nantucket Memorial Airport",
  "ACT": "Waco Regional Airport",
  "ACV": "California Redwood Coast-Humboldt County Airport",
  "ACY": "Atlantic City International Airport",
  "ADK": "Adak Airport",
  "ADQ": "Kodiak Airport",
  "AEX": "Alexandria International Airport",
  "AGS": "Augusta Regional At Bush Field",
  "AIA": "Alliance Municipal Airport",
  "AKB": "Atka Airport",
  "AKN": "King Salmon Airport",
  "ALB": "Albany International Airport",
  "ALO": "Waterloo Regional Airport",
  "ALS": "San Luis Valley Regional Bergman Field",
  "ALW": "Walla Walla Regional Airport",
  "AMA": "Rick Husband Amarillo International Airport",
  "ANC": "Ted Stevens Anchorage International Airport",
  "ANI": "Aniak Airport",
  "AOO": "Altoona Blair County Airport",
  "APN": "Alpena County Regional Airport",
  "ART": "Watertown International Airport",
  "ASE": "Aspen-Pitkin Co/Sardy Field",
  "ATL": "Hartsfield Jackson Atlanta International Airport",
  "ATW": "Appleton International Airport",
  "ATY": "Watertown Regional Airport",
  "AUG": "Augusta State Airport",
  "AUS": "Austin Bergstrom International Airport",
  "AVL": "Asheville Regional Airport",
  "AVP": "Wilkes Barre Scranton International Airport",
  "AZA": "Phoenix-Mesa-Gateway Airport",
  "AZO": "Kalamazoo Battle Creek International Airport",
  "BDL": "Bradley International Airport",
  "BET": "Bethel Airport",
  "BFD": "Bradford Regional Airport",
  "BFF": "Western Neb. Rgnl/William B. Heilig Airport",
  "BFL": "Meadows Field",
  "BFM": "Mobile Downtown Airport",
  "BGM": "Greater Binghamton/Edwin A Link field",
  "BGR": "Bangor International Airport",
  "BHB": "Hancock County-Bar Harbor Airport",
  "BHM": "Birmingham-Shuttlesworth International Airport",
  "BIH": "Eastern Sierra Regional Airport",
  "BIL": "Billings Logan International Airport",
  "BIS": "Bismarck Municipal Airport",
  "BJI": "Bemidji Regional Airport",
  "BKW": "Raleigh County Memorial Airport",
  "BLI": "Bellingham International Airport",
  "BLV": "Scott AFB/Midamerica Airport",
  "BMI": "Central Illinois Regional Airport at Bloomington-Normal",
  "BNA": "Nashville International Airport",
  "BOI": "Boise Air Terminal/Gowen field",
  "BOS": "General Edward Lawrence Logan International Airport",
  "BPT": "Jack Brooks Regional Airport",
  "BQK": "Brunswick Golden Isles Airport",
  "BQN": "Rafael Hernandez Airport",
  "BRD": "Brainerd Lakes Regional Airport",
  "BRL": "Southeast Iowa Regional Airport",
  "BRO": "Brownsville South Padre Island International Airport",
  "BRW": "Wiley Post Will Rogers Memorial Airport",
  "BTM": "Bert Mooney Airport",
  "BTR": "Baton Rouge Metropolitan Ryan Field",
  "BTV": "Patrick Leahy Burlington International Airport",
  "BUF": "Buffalo Niagara International Airport",
  "BUR": "Bob Hope Airport",
  "BWI": "Baltimore/Washington International Thurgood Marshal Airport",
  "BZN": "Bozeman Yellowstone International Airport",
  "CAE": "Columbia Metropolitan Airport",
  "CAK": "Akron Canton Regional Airport",
  "CDB": "Cold Bay Airport",
  "CDC": "Cedar City Regional Airport",
  "CDR": "Chadron Municipal Airport",
  "CDV": "Merle K (Mudhole) Smith Airport",
  "CEC": "Jack Mc Namara Field Airport",
  "CEZ": "Cortez Municipal Airport",
  "CHA": "Lovell Field",
  "CHO": "Charlottesville Albemarle Airport",
  "CHS": "Charleston Air Force Base-International Airport",
  "CIC": "Chico Municipal Airport",
  "CID": "The Eastern Iowa Airport",
  "CIU": "Chippewa County International Airport",
  "CKB": "North Central West Virginia Airport",
  "CLD": "Mc Clellan-Palomar Airport",
  "CLE": "Cleveland Hopkins International Airport",
  "CLL": "Easterwood Field",
  "CLT": "Charlotte Douglas International Airport",
  "CMH": "John Glenn Columbus International Airport",
  "CMI": "University of Illinois Willard Airport",
  "CMX": "Houghton County Memorial Airport",
  "CNY": "Canyonlands Field",
  "COD": "Yellowstone Regional Airport",
  "COS": "City of Colorado Springs Municipal Airport",
  "COU": "Columbia Regional Airport",
  "CPR": "Casper-Natrona County International Airport",
  "CPX": "Benjamin Rivera Noriega Airport",
  "CRP": "Corpus Christi International Airport",
  "CRW": "Yeager Airport",
  "CSG": "Columbus Metropolitan Airport",
  "CVG": "Cincinnati Northern Kentucky International Airport",
  "CVN": "Clovis Municipal Airport",
  "CWA": "Central Wisconsin Airport",
  "CYS": "Cheyenne Regional Jerry Olson Field",
  "DAB": "Daytona Beach International Airport",
  "DAL": "Dallas Love Field",
  "DAY": "James M Cox Dayton International Airport",
  "DBQ": "Dubuque Regional Airport",
  "DCA": "Ronald Reagan Washington National Airport",
  "DDC": "Dodge City Regional Airport",
  "DEC": "Decatur Airport",
  "DEN": "Denver International Airport",
  "DFW": "Dallas Fort Worth International Airport",
  "DHN": "Dothan Regional Airport",
  "DIK": "Dickinson Theodore Roosevelt Regional Airport",
  "DLG": "Dillingham Airport",
  "DLH": "Duluth International Airport",
  "DRO": "Durango La Plata County Airport",
  "DRT": "Del Rio International Airport",
  "DSM": "Des Moines International Airport",
  "DTW": "Detroit Metropolitan Wayne County Airport",
  "DUJ": "DuBois Regional Airport",
  "DUT": "Unalaska Airport",
  "DVL": "Devils Lake Regional Airport",
  "EAR": "Kearney Regional Airport",
  "EAT": "Pangborn Memorial Airport",
  "EAU": "Chippewa Valley Regional Airport",
  "ECP": "Northwest Florida Beaches International Airport",
  "EGE": "Eagle County Regional Airport",
  "EKO": "Elko Regional Airport",
  "ELM": "Elmira Corning Regional Airport",
  "ELP": "El Paso International Airport",
  "ENA": "Kenai Municipal Airport",
  "ERI": "Erie International Tom Ridge Field",
  "ESC": "Delta County Airport",
  "EUG": "Mahlon Sweet Field",
  "EVV": "Evansville Regional Airport",
  "EWN": "Coastal Carolina Regional Airport",
  "EWR": "Newark Liberty International Airport",
  "EYW": "Key West International Airport",
  "FAI": "Fairbanks International Airport",
  "FAR": "Hector International Airport",
  "FAT": "Fresno Yosemite International Airport",
  "FAY": "Fayetteville Regional Grannis Field",
  "FCA": "Glacier Park International Airport",
  "FKL": "Venango Regional Airport",
  "FLG": "Flagstaff Pulliam Airport",
  "FLL": "Fort Lauderdale Hollywood International Airport",
  "FLO": "Florence Regional Airport",
  "FMN": "Four Corners Regional Airport",
  "FNL": "Northern Colorado Regional Airport",
  "FNT": "Bishop International Airport",
  "FOD": "Fort Dodge Regional Airport",
  "FSD": "Joe Foss Field Airport",
  "FSM": "Fort Smith Regional Airport",
  "FWA": "Fort Wayne International Airport",
  "FYV": "Drake Field",
  "GBD": "Great Bend Municipal Airport",
  "GCC": "Northeast Wyoming Regional Airport",
  "GCK": "Garden City Regional Airport",
  "GEG": "Spokane International Airport",
  "GFK": "Grand Forks International Airport",
  "GGG": "East Texas Regional Airport",
  "GJT": "Grand Junction Regional Airport",
  "GLH": "Greenville Mid-Delta Airport",
  "GNV": "Gainesville Regional Airport",
  "GPT": "Gulfport Biloxi International Airport",
  "GRB": "Austin Straubel International Airport",
  "GRI": "Central Nebraska Regional Airport",
  "GRK": "Robert Gray  Army Air Field Airport",
  "GRR": "Gerald R. Ford International Airport",
  "GSO": "Piedmont Triad International Airport",
  "GSP": "Greenville Spartanburg International Airport",
  "GTF": "Great Falls International Airport",
  "GTR": "Golden Triangle Regional Airport",
  "GUC": "Gunnison Crested Butte Regional Airport",
  "GUM": "Antonio B. Won Pat International Airport",
  "HDN": "Yampa Valley Airport",
  "HGR": "Hagerstown Regional Richard A Henson Field",
  "HHH": "Hilton Head Airport",
  "HIB": "Range Regional Airport",
  "HLN": "Helena Regional Airport",
  "HNL": "Honolulu International Airport",
  "HOB": "Lea County Regional Airport",
  "HOM": "Homer Airport",
  "HON": "Huron Regional Airport",
  "HOU": "William P Hobby Airport",
  "HPN": "Westchester County Airport",
  "HRL": "Valley International Airport",
  "HSV": "Huntsville International Carl T Jones Field",
  "HTS": "Tri-State/Milton J. Ferguson Field",
  "HVN": "Tweed New Haven Airport",
  "HYA": "Cape Cod Gateway Airport",
  "HYS": "Hays Regional Airport",
  "IAD": "Washington Dulles International Airport",
  "IAG": "Niagara Falls International Airport",
  "IAH": "George Bush Intercontinental Houston Airport",
  "ICT": "Wichita Mid Continent Airport",
  "IDA": "Idaho Falls Regional Airport",
  "IFP": "Laughlin Bullhead International Airport",
  "ILG": "New Castle Airport",
  "ILM": "Wilmington International Airport",
  "IMT": "Ford Airport",
  "IND": "Indianapolis International Airport",
  "INL": "Falls International Airport",
  "IPL": "Imperial County Airport",
  "IPT": "Williamsport Regional Airport",
  "ISN": "Sloulin Field International Airport",
  "ISP": "Long Island Mac Arthur Airport",
  "ITH": "Ithaca Tompkins Regional Airport",
  "ITO": "Hilo International Airport",
  "IYK": "Inyokern Airport",
  "JAC": "Jackson Hole Airport",
  "JAN": "Jackson Evers International Airport",
  "JAX": "Jacksonville International Airport",
  "JFK": "John F Kennedy International Airport",
  "JHM": "Kapalua Airport",
  "JHW": "Chautauqua County-Jamestown Airport",
  "JLN": "Joplin Regional Airport",
  "JMS": "Jamestown Regional Airport",
  "JNU": "Juneau International Airport",
  "JST": "John Murtha Johnstown Cambria County Airport",
  "KOA": "Kona International At Keahole Airport",
  "KTN": "Ketchikan International Airport",
  "LAL": "Lakeland Linder Regional Airport",
  "LAN": "Capital Region International Airport",
  "LAR": "Laramie Regional Airport",
  "LAS": "Harry Reid International Airport",
  "LAW": "Lawton Fort Sill Regional Airport",
  "LAX": "Los Angeles International Airport",
  "LBB": "Lubbock Preston Smith International Airport",
  "LBE": "Arnold Palmer Regional Airport",
  "LBF": "North Platte Regional Airport Lee Bird Field",
  "LBL": "Liberal Mid-America Regional Airport",
  "LCH": "Lake Charles Regional Airport",
  "LCK": "Rickenbacker International Airport",
  "LEB": "Lebanon Municipal Airport",
  "LEX": "Blue Grass Airport",
  "LFT": "Lafayette Regional Airport",
  "LGA": "La Guardia Airport",
  "LGB": "Long Beach /Daugherty Field/ Airport",
  "LIH": "Lihue Airport",
  "LIT": "Adams Field",
  "LMT": "Crater Lake/Klamath Regional Airport",
  "LNK": "Lincoln Airport",
  "LNS": "Lancaster Airport",
  "LNY": "Lanai Airport",
  "LRD": "Laredo International Airport",
  "LSE": "La Crosse Municipal Airport",
  "LWB": "Greenbrier Valley Airport",
  "LWS": "Lewiston Nez Perce County Airport",
  "LWT": "Lewistown Municipal Airport",
  "LYH": "Lynchburg Regional Preston Glenn Field",
  "MAF": "Midland International Air and Space Port Airport",
  "MAZ": "Eugenio Maria De Hostos Airport",
  "MBS": "MBS International Airport",
  "MCG": "McGrath Airport",
  "MCI": "Kansas City International Airport",
  "MCK": "Mc Cook Ben Nelson Regional Airport",
  "MCN": "Middle Georgia Regional Airport",
  "MCO": "Orlando International Airport",
  "MCW": "Mason City Municipal Airport",
  "MDT": "Harrisburg International Airport",
  "MDW": "Chicago Midway International Airport",
  "MEI": "Key Field",
  "MEM": "Memphis International Airport",
  "MFE": "Mc Allen Miller International Airport",
  "MFR": "Rogue Valley International Medford Airport",
  "MGM": "Montgomery Regional (Dannelly Field) Airport",
  "MGW": "Morgantown Municipal Walter L. Bill Hart Field",
  "MHK": "Manhattan Regional Airport",
  "MHT": "Manchester Boston Regional Airport",
  "MIA": "Miami International Airport",
  "MKE": "General Mitchell International Airport",
  "MKG": "Muskegon County Airport",
  "MKK": "Molokai Airport",
  "MLB": "Melbourne Orlando International Airport",
  "MLI": "Quad City International Airport",
  "MLS": "Frank Wiley Field",
  "MLU": "Monroe Regional Airport",
  "MMH": "Mammoth Yosemite Airport",
  "MOB": "Mobile Regional Airport",
  "MOD": "Modesto City Co-Harry Sham Field",
  "MOT": "Minot International Airport",
  "MQT": "Sawyer International Airport",
  "MRY": "Monterey Peninsula Airport",
  "MSL": "Northwest Alabama Regional Airport",
  "MSN": "Dane County Regional Truax Field",
  "MSO": "Missoula International Airport",
  "MSP": "Minneapolis-St Paul International/Wold-Chamberlain Airport",
  "MSY": "Louis Armstrong New Orleans International Airport",
  "MTJ": "Montrose Regional Airport",
  "MVY": "Martha's Vineyard Airport",
  "MYR": "Myrtle Beach International Airport",
  "OAJ": "Albert J Ellis Airport",
  "OAK": "Metropolitan Oakland International Airport",
  "OGD": "Ogden Hinckley Airport",
  "OGG": "Kahului Airport",
  "OGS": "Ogdensburg International Airport",
  "OKC": "Will Rogers World Airport",
  "OMA": "Eppley Airfield",
  "OME": "Nome Airport",
  "ONT": "Ontario International Airport",
  "ORD": "Chicago O'Hare International Airport",
  "ORF": "Norfolk International Airport",
  "ORH": "Worcester Regional Airport",
  "OTH": "Southwest Oregon Regional Airport",
  "OTZ": "Ralph Wien Memorial Airport",
  "OXR": "Oxnard Airport",
  "PAE": "Snohomish County (Paine Field) Airport",
  "PAH": "Barkley Regional Airport",
  "PBG": "Plattsburgh International Airport",
  "PBI": "Palm Beach International Airport",
  "PDT": "Eastern Oregon Regional At Pendleton Airport",
  "PDX": "Portland International Airport",
  "PFN": "Panama City-Bay Co International Airport",
  "PGA": "Page Municipal Airport",
  "PGD": "Punta Gorda Airport",
  "PGV": "Pitt Greenville Airport",
  "PHF": "Newport News Williamsburg International Airport",
  "PHL": "Philadelphia International Airport",
  "PHX": "Phoenix Sky Harbor International Airport",
  "PIA": "Greater Peoria Regional Airport",
  "PIB": "Hattiesburg Laurel Regional Airport",
  "PIE": "St Petersburg Clearwater International Airport",
  "PIH": "Pocatello Regional Airport",
  "PIR": "Pierre Regional Airport",
  "PIT": "Pittsburgh International Airport",
  "PKB": "Mid Ohio Valley Regional Airport",
  "PLN": "Pellston Regional Airport of Emmet County Airport",
  "PMD": "Palmdale Regional/USAF Plant 42 Airport",
  "PNS": "Pensacola Regional Airport",
  "PPG": "Pago Pago International Airport",
  "PQI": "Presque Isle International Airport",
  "PRC": "Ernest A. Love Field",
  "PSC": "Tri Cities Airport",
  "PSE": "Mercedita Airport",
  "PSG": "Petersburg James A Johnson Airport",
  "PSM": "Portsmouth International at Pease Airport",
  "PSP": "Palm Springs International Airport",
  "PUB": "Pueblo Memorial Airport",
  "PUW": "Pullman Moscow Regional Airport",
  "PVC": "Provincetown Municipal Airport",
  "PVD": "Rhode Island TF Green International Airport",
  "PVU": "Provo Municipal Airport",
  "PWM": "Portland International Jetport Airport",
  "RAP": "Rapid City Regional Airport",
  "RDD": "Redding Municipal Airport",
  "RDM": "Roberts Field",
  "RDU": "Raleigh Durham International Airport",
  "RFD": "Chicago Rockford International Airport",
  "RHI": "Rhinelander Oneida County Airport",
  "RIC": "Richmond International Airport",
  "RIW": "Central Wyoming Regional Airport",
  "RKD": "Knox County Regional Airport",
  "RKS": "Southwest Wyoming Regional Airport",
  "RNO": "Reno Tahoe International Airport",
  "ROA": "Roanoke Regional Woodrum Field",
  "ROC": "Greater Rochester International Airport",
  "ROW": "Roswell International Air Center Airport",
  "RST": "Rochester International Airport",
  "RSW": "Southwest Florida International Airport",
  "RUT": "Rutland - Southern Vermont Regional Airport",
  "SAF": "Santa Fe Municipal Airport",
  "SAN": "San Diego International Airport",
  "SAT": "San Antonio International Airport",
  "SAV": "Savannah Hilton Head International Airport",
  "SBA": "Santa Barbara Municipal Airport",
  "SBD": "San Bernardino International Airport",
  "SBN": "South Bend Regional Airport",
  "SBP": "San Luis County Regional Airport",
  "SBY": "Salisbury Ocean City Wicomico Regional Airport",
  "SCC": "Deadhorse Airport",
  "SCE": "State College Regional Airport",
  "SCK": "Stockton Metropolitan Airport",
  "SDF": "Louisville Muhammad Ali International Airport",
  "SDP": "Sand Point Airport",
  "SDY": "Sidney Richland Municipal Airport",
  "SEA": "Seattle Tacoma International Airport",
  "SFB": "Orlando Sanford International Airport",
  "SFO": "San Francisco International Airport",
  "SGF": "Springfield Branson National Airport",
  "SGU": "St George Municipal Airport",
  "SHD": "Shenandoah Valley Regional Airport",
  "SHR": "Sheridan County Airport",
  "SHV": "Shreveport Regional Airport",
  "SIT": "Sitka Rocky Gutierrez Airport",
  "SJC": "Norman Y. Mineta San Jose International Airport",
  "SJT": "San Angelo Regional Mathis Field",
  "SJU": "Luis Munoz Marin International Airport",
  "SLC": "Salt Lake City International Airport",
  "SLE": "McNary Field",
  "SLK": "Adirondack Regional Airport",
  "SLN": "Salina Municipal Airport",
  "SMF": "Sacramento International Airport",
  "SMX": "Santa Maria Pub/Capt G Allan Hancock Field",
  "SNA": "John Wayne Airport-Orange County Airport",
  "SNP": "St Paul Island Airport",
  "SOW": "Show Low Regional Airport",
  "SPI": "Abraham Lincoln Capital Airport",
  "SPN": "Francisco C. Ada Saipan International Airport",
  "SPS": "Sheppard Air Force Base-Wichita Falls Municipal Airport",
  "SRQ": "Sarasota Bradenton International Airport",
  "STC": "St Cloud Regional Airport",
  "STL": "Lambert St Louis International Airport",
  "STS": "Charles M. Schulz Sonoma County Airport",
  "STT": "Cyril E. King Airport",
  "STX": "Henry E Rohlsen Airport",
  "SUN": "Friedman Memorial Airport",
  "SUX": "Sioux Gateway Col. Bud Day Field",
  "SVC": "Grant County Airport",
  "SWF": "Stewart International Airport",
  "SWO": "Stillwater Regional Airport",
  "SYR": "Syracuse Hancock International Airport",
  "TBN": "Waynesville-St. Robert Regional Forney field",
  "TEX": "Telluride Regional Airport",
  "TLH": "Tallahassee Regional Airport",
  "TOL": "Toledo Express Airport",
  "TPA": "Tampa International Airport",
  "TRI": "Tri Cities Regional Tn Va Airport",
  "TTN": "Trenton Mercer Airport",
  "TUL": "Tulsa International Airport",
  "TUP": "Tupelo Regional Airport",
  "TUS": "Tucson International Airport",
  "TVC": "Cherry Capital Airport",
  "TVF": "Thief River Falls Regional Airport",
  "TWF": "Joslin Field Magic Valley Regional Airport",
  "TXK": "Texarkana Regional Webb Field",
  "TYR": "Tyler Pounds Regional Airport",
  "TYS": "McGhee Tyson Airport",
  "UNK": "Unalakleet Airport",
  "USA": "Concord Regional Airport",
  "VCT": "Victoria Regional Airport",
  "VDZ": "Valdez Pioneer Field",
  "VEL": "Vernal Regional Airport",
  "VIS": "Visalia Municipal Airport",
  "VLD": "Valdosta Regional Airport",
  "VPS": "Eglin Air Force Base",
  "VQS": "Antonio Rivera Rodriguez Airport",
  "VRB": "Vero Beach Municipal Airport",
  "WRG": "Wrangell Airport",
  "WRL": "Worland Municipal Airport",
  "XNA": "Northwest Arkansas Regional Airport",
  "XWA": "Williston Basin International Airport",
  "YAK": "Yakutat Airport",
  "YKM": "Yakima Air Terminal McAllister Field",
  "YNG": "Youngstown Warren Regional Airport",
  "YUM": "Yuma MCAS/Yuma International Airport",
  "JRB": "Downtown Manhattan Heliport",
  "TSS": "East 34th Street Heliport",
};

export function normalizeAirportCode(code: string): string {
  return String(code || "").trim().toUpperCase();
}

export function getAirportName(code: string): string | null {
  const normalized = normalizeAirportCode(code);
  return AIRPORT_LOOKUP[normalized] ?? null;
}

export function getAirportDisplayName(code: string): string {
  const normalized = normalizeAirportCode(code);
  if (!normalized) {
    return "";
  }
  const name = getAirportName(normalized);
  return name ? `${normalized} - ${name}` : normalized;
}

export function formatRouteDisplay(origin: string, dest: string): string {
  return `${getAirportDisplayName(origin)} -> ${getAirportDisplayName(dest)}`;
}
